export const DATA_1 = [
  {
    id: 1,
    image: "./home1.jpg",
    restaurantsName: "Pizza Hut",
    place: "Taman XXX",
    deliveryTime: "45 mins",
    distance: "2.2km",
    rating: "4.5",
    percenterOff: 30,
    rmOff: 2.00,
  },
  {
    id: 2,
    image: "./home2.jpg",
    restaurantsName: "Subway",
    place: "Taman XXX",
    deliveryTime: "30 mins",
    distance: "1km",
    rating: "4.2",
    percenterOff: 10,
    rmOff: 10.00,
  },
  {
    id: 3,
    image: "./home1.jpg",
    restaurantsName: "DFC",
    place: "Taman XXX",
    deliveryTime: "20 mins",
    distance: "11km",
    rating: "3.2",
    percenterOff: 50,
    rmOff: 3.00,
  },
];

export const DATA_2 = [
  {
    id: 1,
    image: "./home4.jpg",
    foodName: "CHAGEE",
    rating: "3.0",
    catergory: "Beverage",
    freeDelivery: true,
    deliveryPrice: 2.00,
    place: "Taman XXX",
    saver: true,
    promo: true,
    deliveryTime:"40 mins",
    outlet:[{
      id: 1,
      image: "./home4.jpg",
      foodName: "CHAGEE",
      rating: "3.0",
      catergory: "Beverage",
      freeDelivery: true,
      deliveryPrice: 2.00,
      place: "Taman Connaught",
      saver: true,
      promo: true,
      deliveryTime:"40 mins",
    },{
      id: 2,
      image: "./home4.jpg",
      foodName: "CHAGEE",
      rating: "4.2",
      catergory: "Beverage",
      freeDelivery: true,
      deliveryPrice: 4.00,
      place: "Lot 10",
      saver: true,
      promo: true,
      deliveryTime:"60 mins",
    },{
      id: 3,
      image: "./home4.jpg",
      foodName: "CHAGEE",
      rating: "3.0",
      catergory: "Beverage",
      freeDelivery: true,
      deliveryPrice: 4.00,
      place: "Pandan Indah",
      saver: true,
      promo: true,
      deliveryTime:"60 mins",
    },{
      id: 4,
      image: "./home4.jpg",
      foodName: "CHAGEE",
      rating: "3.0",
      catergory: "Beverage",
      freeDelivery: true,
      deliveryPrice: 4.00,
      place: "Pandan Indah",
      saver: true,
      promo: true,
      deliveryTime:"60 mins",
    },{
      id: 5,
      image: "./home4.jpg",
      foodName: "CHAGEE",
      rating: "3.0",
      catergory: "Beverage",
      freeDelivery: true,
      deliveryPrice: 4.00,
      place: "Pandan Indah",
      saver: true,
      promo: true,
      deliveryTime:"60 mins",
    },],
  },
  {
    id: 2,
    image: "./home4.jpg",
    foodName: "CHAGEE",
    rating: "3.0",
    catergory: "Beverage",
    freeDelivery: true,
    deliveryPrice: 3.00,
    place: "Taman XXX",
    saver: true,
    promo: true,
    deliveryTime:"40 mins",
    outlet:[],
  },
  {
    id: 3,
    image: "./home4.jpg",
    foodName: "CHAGEE",
    rating: "3.0",
    catergory: "Beverage",
    freeDelivery: true,
    deliveryPrice: 2.00,
    place: "Taman XXX",
    saver: true,
    promo: true,
    deliveryTime:"40 mins",
    outlet:[],
  },
];

export const HOME_SLIDE = [
  {
    id: 1,
    image: "./home3.jpg",
    title: "Order Now",
    desc:"Get more for less",
    name: "sarawak cafe",
  },
  {
    id: 2,
    image: "./home3.jpg",
    title: "Get it Now",
    desc:"Get more for less",
    name: "sarawak cafe",
  },
  {
    id: 3,
    image: "./home3.jpg",
    title: "Buy now",
    desc:"Get more for less",
    name: "sarawak cafe",
  },
]
