export const DATA = [
  {
    id: 1,
    image: "./home1.jpg",
    restaurantsName: "Pizza Hut",
    place: "Taman XXX",
    deliveryTime: "45 mins",
    distance: "2.2km",
    rating: "4.5",
    percenterOff: "30% off",
    rmOff: "RM2.00 off",
  },
  {
    id: 2,
    image: "./home2.jpg",
    restaurantsName: "Subway",
    place: "Taman XXX",
    deliveryTime: "30 mins",
    distance: "1km",
    rating: "4.2",
    percenterOff: "10% off",
    rmOff: "RM10.00 off",
  },
  {
    id: 3,
    image: "./home1.jpg",
    restaurantsName: "DFC",
    place: "Taman XXX",
    deliveryTime: "20 mins",
    distance: "11km",
    rating: "3.2",
    percenterOff: "50% off",
    rmOff: "RM3.00 off",
  },
];
